---
default_stages: [commit, push]
default_language_version:
  python: python3
  node: 18.6.0
minimum_pre_commit_version: "2.0.0"
repos:
  - repo: meta
    hooks:
      - id: identity
        name: Print input to the static check hooks for troubleshooting
      - id: check-hooks-apply
        name: Check if all hooks apply to the repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: Run isort to sort imports in Python files
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
        args:
          - --check
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
        args:
          - --config
          - ./pyproject.toml
          - --check
  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python3
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        name: Check that merge conflicts are not being committed
      - id: debug-statements
        name: Detect accidentally committed debug statements
      - id: check-builtin-literals
        name: Require literal syntax when initializing Python builtin types
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
      - id: detect-private-key
        name: Detect if private key is added to the repository
      - id: end-of-file-fixer
        name: Make sure that there is an empty line at the end
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
      - id: mixed-line-ending
        name: Detect if mixed line ending is used (\r vs. \r\n)
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
      - id: trailing-whitespace
        name: Remove trailing whitespace at end of line
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
      - id: fix-encoding-pragma
        name: Remove encoding header from python files
        exclude: airflow_provider_azure_machinelearning/example_dags/dags_data
        args:
          - --remove
      - id: pretty-format-json
        name: Format json files
        args:
          - --autofix
          - --no-sort-keys
          - --indent
          - "4"
        files: \.json$
        pass_filenames: true
