name: dev
channels:
  - defaults
dependencies:
  - python=3.7
  - pip:
    - apache-airflow>=2.0.0
    - azure-ai-ml>=1.0.0
    - black
    - flake8
    - pytest
    - pre-commit
    - setuptools
    - twine
    - wheel
